Update test.yml
update yaml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -41,6 +41,10 @@ jobs:
     
             # Fetch the correct ChromeDriver version for the major version
             CHROME_DRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_VERSION")
+            if [ -z "$CHROME_DRIVER_VERSION" ]; then
+              echo "Error: Could not retrieve ChromeDriver version"
+              exit 1
+            fi
             echo "ChromeDriver version: $CHROME_DRIVER_VERSION"
     
             # Download and install ChromeDriver
